### ISSUE TITLE
Make Annual Appointment: Design

### ISSUE THREAD

**Issue by Lussier115** [aa-software2112/SOEN_344#12]
Base Issue: #6

**Comment by aa-software2112** [comment]
https://www.draw.io/?state=%7B%22ids%22:%5B%221L-MKzTXsnDK_KTySF9pE6zEnNhww01K5%22%5D,%22action%22:%22open%22,%22userId%22:%22111941182143072512528%22%7D#G1L-MKzTXsnDK_KTySF9pE6zEnNhww01K5
