### ISSUE TITLE
Display personel and availabilities for a specific clinic

### ISSUE THREAD

**Issue by samgo1** [aa-software2112/SOEN_344#126]
For a specific clinic display the doctors and nurses that are assigned there and display the availabilities for that clinic

**Comment by samgo1** [comment]
Should be something an admin can do, therefore a button should be added to navbar for the admin

**Comment by KrishnaPatel1** [comment]
Is anybody doing this at the moment? @samgo1

**Comment by samgo1** [comment]
@KrishnaPatel1 im taking it

**Comment by samgo1** [comment]
@laurawheatley this issue is related to the 3rd requirements of the milestone 2 : 
 _Different clinics with internal representation of schedule, number of personal (doctors, nurses) and
rooms._

I think they want a way that we can display for each clinic, the employees that work there and the availabilities, I think that only the admin should have the right to do that so I was thinking having a button top right on the navbar for him. You can implement it the way you want, that was my initial thinking on the issue
