### ISSUE TITLE
Ensure all new Clinic Changes Work with all Previous Use Cases

### ISSUE THREAD

**Issue by KrishnaPatel1** [aa-software2112/SOEN_344#137]
- [x] Sign up Patient @laurawheatley 
- [x] Sign up Doctor/Nurse through Admin @laurawheatley 
- [x] Log-in Patient/Doctor/Nurse/Admin @laurawheatley 
- [x] Make Appointment (patient)  @aa-software2112 
- [x] Update Appointment (patient) @aa-software2112 
- [x] Cancel Appointment (patient) @aa-software2112 
- [x] Manage Cart (patient) @lkadian 
- [x] Make Availability (doctor) @KrishnaPatel1 
- [x] Update Availability (doctor) @KrishnaPatel1 
- [x] Cancel Availability (doctor) @KrishnaPatel1 
- [x] View Patient Booking (nurse, patient) @samgo1 , @Lussier115 
- [x] Update Patient Booking (nurse, patient) @samgo1 , @Lussier115 
- [x] Cancel Patient Booking (nurse, patient) @samgo1 , @Lussier115 
- [x] Book Patient Appointment (nurse) @samgo1

**Comment by aa-software2112** [comment]
All updates for my three parts above were merged into master
