### ISSUE TITLE
Make Walk-In Appointment: Design

### ISSUE THREAD

**Issue by Lussier115** [aa-software2112/SOEN_344#21]
Base Issue: #8 

Interaction diagram

**Comment by aa-software2112** [comment]
https://www.draw.io/?state=%7B%22ids%22:%5B%221C0MMfcc0HMAONNBDyp02NYbSZDxdiz4t%22%5D,%22action%22:%22open%22,%22userId%22:%22111941182143072512528%22%7D#G1C0MMfcc0HMAONNBDyp02NYbSZDxdiz4t

**Comment by aa-software2112** [comment]
![image](https://user-images.githubusercontent.com/22150653/52612948-d6aade00-2e59-11e9-8a0b-0d81e0d0d118.png)
Always refer to link for most recent version
