### ISSUE TITLE
Update Class Diagram and Source Code 

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN_344#45]
Changes were made to interaction diagrams 
1. [x] Remove from cart
2. [x] Update Booking 
3. [x] Checkout Appointment
4. [x] Cancel Booking

- [x] @aa-software2112 - Scheduler needs to change reserveAppointment method to take an availability id
- [x] @aa-software2112 - Scheduler needs to change parameter for freeAvailability
- [x] @lkadian - Booking Service -> cancelBooking now returns a single integer, which is the availability id of the cancelled booking
- [x] @lkadian - Booking Service -> writeBooking now takes an availability object (contains the availability id and doctor id of the new booking), and a patient id that can be used to construct the booking row in the booking table

**Comment by KrishnaPatel1** [comment]
Can this be closed? @lkadian  @samgo1  @aa-software2112
