### ISSUE TITLE
Front End: Login Doctor, Nurse, Patient, Register Patient

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN_344#51]
Create both of the following components:

- [ ] Navbar w/ cookie integration
- [ ] Footer
- [ ] Component to login - different for Doctor, Nurse, Patient.
- [ ] Component to register patient which includes all the attributes required in the class

**Comment by aa-software2112** [comment]
- [ ] Register Nurse
- [ ] Register Patient
- [ ] Register Doctor
- [ ] Login Patient
- [ ] Login Doctor
- [ ] Login Nurse

**Comment by KrishnaPatel1** [comment]
Mockup
![Mockup](https://user-images.githubusercontent.com/25628075/53034817-081b3f00-3442-11e9-8d67-8a27c6fad225.jpg)

**Comment by Lussier115** [comment]
I will implement the Landing Page as seen in the above mock tomorrow morning.
