### ISSUE TITLE
Front End: Cart Component

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN_344#52]
Create a car component which contains the following:

- [x] Listing an appointment with its date and appointment type
- [x] Create buttons beside each appointment to ~~update~~ or cancel the appointment
- [x] Create a checkout button to book all the appointments in the cart

**Comment by KrishnaPatel1** [comment]
Mockup
![Mockup](https://user-images.githubusercontent.com/25628075/53034837-1a957880-3442-11e9-8f47-5a76b8c08c3a.jpg)

**Comment by samgo1** [comment]
PR open #83
