### ISSUE TITLE
Cancel Doctor Availability - Design Diagram

### ISSUE THREAD

**Issue by KrishnaPatel1** [aa-software2112/SOEN_344#77]
Make the appropriate diagram for the `Modify Doctor Availability` story #55

**Comment by samgo1** [comment]
> Make the appropriate diagram for the `Modify Doctor Availability` story #55

@KrishnaPatel1 this is Cancel Doctor Availability, I think you made a mistake on the issue description

**Comment by samgo1** [comment]
[diagram](https://www.draw.io/?state=%7B%22folderId%22:%221-4mxbzB8KoaIWzrAbkfC6VM1Z7f9r3gq%22,%22action%22:%22create%22,%22userId%22:%22118201170449242892321%22%7D#G12w1_c-l3xfzZo9XSmFqMtwHtDuJPPPzQ)
